<a href="https://colab.research.google.com/github/Rahi20028/learning-AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import library
import numpy as np

#list
l1 = [1,2,3,4,5]
l1

[1, 2, 3, 4, 5]

In [2]:
x = np.array(list)
print(x)

<class 'list'>


#compare list and numpy


In [3]:
from time import process_time
# find time taken by list
list1= [i for i in range(10000000)]
start_time=process_time()
list1=[i+10 for i in list1] #add 10 to each no.
end_time=process_time()
print(end_time-start_time)
#print(list1)

0.7549508299999999


In [4]:
#find time taken by the numpy array
array=np.array([i for i in range(10000000)])
start=process_time()
array+=10
end=process_time()
print(end-start - start_time)

-3.587641331000001


In [5]:
#find the type of list and array
print(type(list1))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
#create 1D array with 5 elements
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [7]:
#generate random value
x=np.random.rand(5)
print(x)

[0.53975904 0.66621046 0.25654122 0.61890642 0.21159051]


In [8]:
#generate random value from range 5 to 15 with 1D array size 10
#randint(first arg=low, second= high-1, no. of elements)
x=np.random.randint(5,16,10)
print(x)

[11  5  9  6 15 15  5  5  6  6]


In [9]:
#create 2D array - 4 by 3
y=np.array([[1,2,3],[4,5,6],[7,8,9],[9,4,2]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 4 2]]


In [10]:
#. Generate random value from range 5 to 15 with 2D array size 3 by 3.
y=np.random.randint(5,16,(3,3))
print(y)

[[ 6  7 11]
 [15 14  6]
 [ 5  7  6]]


In [11]:
#assign float value
y=np.array([[1.6,2,3],[4,5,6],[7,8,9],[9,4,2]],dtype=float)
print(y)

[[1.6 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]
 [9.  4.  2. ]]


In [12]:
#create 3D array
z=np.array([[[1,2,3],[4,5,6],[7,8,9],[9,4,2]],[[1,2,3],[4,5,6],[7,8,9],[9,4,2]]])
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [9 4 2]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [9 4 2]]]


In [13]:
a=np.zeros((5,5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
a=np.ones((5,5),dtype=int)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
a=np.full((5,5),4)
print(a)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [16]:
#create identical matrix
a=np.eye(4,5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [17]:
#find shape of array
print("shape of array a is: ", a.shape)

shape of array a is:  (4, 5)


In [18]:
#find dimension of array
x.ndim

1

In [19]:
#find number of elements in array
a.size

20

In [20]:
#find datatype
a.dtype

dtype('int64')

In [21]:
#find maximum from array y
y.max()

np.float64(9.0)

In [22]:
y.min()

np.float64(1.6)

In [23]:
y.argmin()

np.int64(0)

In [24]:
y.mean()

np.float64(5.05)

In [25]:
y

array([[1.6, 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ],
       [9. , 4. , 2. ]])

In [26]:
#find location of maximum from array y
y.argmax()

np.int64(8)

In [27]:
#Create two 2D array of size 3 by 3 and perform four basic mathematical function
a=np.random.randint(10,20,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)

[[11 14 14]
 [15 15 14]
 [13 16 11]]
[[20 23 25]
 [28 28 28]
 [22 29 29]]


In [28]:
print(a+b)

[[31 37 39]
 [43 43 42]
 [35 45 40]]


In [29]:
np.add(a,b)

array([[31, 37, 39],
       [43, 43, 42],
       [35, 45, 40]])

In [30]:
#print(a - b)
np.subtract(a,b)

array([[ -9,  -9, -11],
       [-13, -13, -14],
       [ -9, -13, -18]])

In [31]:
print(a*b)
#np.multiply(a,b)

[[220 322 350]
 [420 420 392]
 [286 464 319]]


In [32]:
#print(a/b)
np.divide(a,b)

array([[0.55      , 0.60869565, 0.56      ],
       [0.53571429, 0.53571429, 0.5       ],
       [0.59090909, 0.55172414, 0.37931034]])

In [33]:
#Print index 2 and -2 value for 1D array. (indexing).
x=np.array([10,12,43,34,54,32])
print(x)
print(x[2])
print(x[-2])

[10 12 43 34 54 32]
43
54


In [34]:
#perform indexing operations with 2D array
y=np.array([[1,2,3],[4,5,6],[6,7,8],[8,9,5]])
print(y)

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [8 9 5]]


In [35]:
print("element at row 0, column 0: ", y[0,0])
print("element at row 0, column 2: ",y[0,2])

element at row 0, column 0:  1
element at row 0, column 2:  3


In [36]:
print("last element in row : ", y[0, -1])
print("Last element in row 2:", y[2, -1])
print("Second-to-last element in row 1:", y[1, -2])

last element in row :  3
Last element in row 2: 8
Second-to-last element in row 1: 5


In [37]:
print(x)
x[2:6]

[10 12 43 34 54 32]


array([43, 34, 54, 32])

In [38]:
x[:5]
x[5:]

array([32])

In [39]:
x[:5]

array([10, 12, 43, 34, 54])

In [40]:
x[5:]

array([32])

In [41]:
x

array([10, 12, 43, 34, 54, 32])

In [42]:
x[5]=100
x

array([ 10,  12,  43,  34,  54, 100])

In [43]:
x[1:8:2]

array([ 12,  34, 100])

In [44]:
slice_array=x[0:5]
slice_array


array([10, 12, 43, 34, 54])

In [45]:
slice_array[:]=99
slice_array

array([99, 99, 99, 99, 99])

In [46]:
np.flip(x)

array([100,  99,  99,  99,  99,  99])

In [47]:
x[::-1]

array([100,  99,  99,  99,  99,  99])

In [48]:
x

array([ 99,  99,  99,  99,  99, 100])

In [49]:
arraycopy= x.copy()
arraycopy

array([ 99,  99,  99,  99,  99, 100])

In [50]:
arraycopy[:]=100
arraycopy

array([100, 100, 100, 100, 100, 100])

In [51]:
x

array([ 99,  99,  99,  99,  99, 100])

In [52]:
arr_2d = np.array([[0,1,2],[3,4,5],[6,7,8]])
subarr= arr_2d[0:,:2]
subarr

array([[0, 1],
       [3, 4],
       [6, 7]])